# Generated by Django 4.2 on 2023-04-29 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TablePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='table',
            name='categories',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('miscellaneous', 'Miscellaneous'), ('wearables', 'Wearables'), ('consumables', 'Consumables'), ('homeables', 'Homeables'), ('gardenables', 'Gardenables'), ('entertainmentables', 'Entertainables')], default='miscellaneous'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_description',
            field=models.TextField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='table',
            name='table_category',
            field=models.CharField(choices=[('miscellaneous', 'Miscellaneous'), ('wearables', 'Wearables'), ('consumables', 'Consumables'), ('homeables', 'Homeables'), ('gardenables', 'Gardenables'), ('entertainmentables', 'Entertainables')], default='miscellaneous'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='tablephoto',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.table'),
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.item'),
        ),
    ]
