# Generated by Django 4.2 on 2023-05-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_checkout_delete_itemphoto_delete_tablephoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(default='', upload_to='item_images/'),
            preserve_default=False,
        ),
    ]
