# Generated by Django 4.2 on 2023-05-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.FileField(default='/static/images/misc.jpg', upload_to='table_images/'),
        ),
    ]
