# Generated by Django 4.2 on 2023-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_cart_alter_item_image_alter_table_image_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='Cart',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='item_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
