# Generated by Django 4.2 on 2023-05-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_cart_cart_item_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart_Item',
            new_name='CartItem',
        ),
    ]
