# Generated by Django 4.2 on 2023-05-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_cartitem_cart_remove_cartitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='cart',
            name='cartItem',
            field=models.ManyToManyField(to='main_app.cartitem'),
        ),
    ]
