# Generated by Django 4.2 on 2023-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_item_image_alter_table_image'),
        ('main_app', '0015_remove_cart_cartitem_delete_order_cart_cartitem'),
    ]

    operations = [
    ]
