# Generated by Django 4.2 on 2023-05-03 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0016_merge_20230503_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='item_review',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='item_rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, max_length=1),
        ),
    ]
