# Generated by Django 4.2 on 2023-05-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_merge_20230503_1317'),
        ('main_app', '0017_remove_review_item_review_review_comment_review_item_and_more'),
    ]

    operations = [
    ]
